spring.application.name=handys-recruit-assignment
server.address=127.0.0.1
spring.datasource.url=jdbc:h2:mem:handys;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=10000
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false
